# permissions for end users to edit vrdbrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vrdbrequest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: vrdbrequest-editor-role
rules:
- apiGroups:
  - jnnkrdb.de
  resources:
  - vrdbrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jnnkrdb.de
  resources:
  - vrdbrequests/status
  verbs:
  - get
