# permissions for end users to edit vaultrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vaultrequest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app
    app.kubernetes.io/part-of: app
    app.kubernetes.io/managed-by: kustomize
  name: vaultrequest-editor-role
rules:
- apiGroups:
  - jnnkrdb.de
  resources:
  - vaultrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jnnkrdb.de
  resources:
  - vaultrequests/status
  verbs:
  - get
