//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMap) DeepCopyInto(out *DataMap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMap.
func (in *DataMap) DeepCopy() *DataMap {
	if in == nil {
		return nil
	}
	out := new(DataMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployedObject) DeepCopyInto(out *DeployedObject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployedObject.
func (in *DeployedObject) DeepCopy() *DeployedObject {
	if in == nil {
		return nil
	}
	out := new(DeployedObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DeployedObjectList) DeepCopyInto(out *DeployedObjectList) {
	{
		in := &in
		*out = make(DeployedObjectList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployedObjectList.
func (in DeployedObjectList) DeepCopy() DeployedObjectList {
	if in == nil {
		return nil
	}
	out := new(DeployedObjectList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacesRegex) DeepCopyInto(out *NamespacesRegex) {
	*out = *in
	if in.MustAvoidRegex != nil {
		in, out := &in.MustAvoidRegex, &out.MustAvoidRegex
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MustMatchRegex != nil {
		in, out := &in.MustMatchRegex, &out.MustMatchRegex
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacesRegex.
func (in *NamespacesRegex) DeepCopy() *NamespacesRegex {
	if in == nil {
		return nil
	}
	out := new(NamespacesRegex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultRequest) DeepCopyInto(out *VaultRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultRequest.
func (in *VaultRequest) DeepCopy() *VaultRequest {
	if in == nil {
		return nil
	}
	out := new(VaultRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultRequestList) DeepCopyInto(out *VaultRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultRequestList.
func (in *VaultRequestList) DeepCopy() *VaultRequestList {
	if in == nil {
		return nil
	}
	out := new(VaultRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultRequestSpec) DeepCopyInto(out *VaultRequestSpec) {
	*out = *in
	if in.DataMap != nil {
		in, out := &in.DataMap, &out.DataMap
		*out = make(map[string]DataMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Namespaces.DeepCopyInto(&out.Namespaces)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultRequestSpec.
func (in *VaultRequestSpec) DeepCopy() *VaultRequestSpec {
	if in == nil {
		return nil
	}
	out := new(VaultRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultRequestStatus) DeepCopyInto(out *VaultRequestStatus) {
	*out = *in
	if in.Deployed != nil {
		in, out := &in.Deployed, &out.Deployed
		*out = make(DeployedObjectList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultRequestStatus.
func (in *VaultRequestStatus) DeepCopy() *VaultRequestStatus {
	if in == nil {
		return nil
	}
	out := new(VaultRequestStatus)
	in.DeepCopyInto(out)
	return out
}
