apiVersion: vaultrdb.jnnkrdb.de/v1
kind: VaultRequest
metadata:
  name: vr-test
data:
  - vaultsetid: testid
    secrets: 
    - name: test1
      namespace: test1
      keyname: hallowelt1
      type: kubernetes.io/basic-auth
      immutable: true
    - name: test2
      namespace: test2
      keyname: hallowelt2
    configmaps: 
    - name: test1
      namespace: test1
      keyname: hallowelt1
      immutable: true
    - name: test2
      namespace: test2
      keyname: hallowelt2
  - vaultsetid: testid_2
    secrets: 
    - name: test1_2
      namespace: test1_2
      keyname: hallowelt1_2
      type: kubernetes.io/basic-auth
      immutable: true
    - name: test2_2
      namespace: test2_2
      keyname: hallowelt2_2
    configmaps: 
    - name: test1_2
      namespace: test1_2
      keyname: hallowelt1_2
      immutable: true
    - name: test2_2
      namespace: test2_2
      keyname: hallowelt2_2

