--- # ------------------------------------------------------------------------------------------- ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-vrdbvault
  labels:
    {{- include "vrdbvault.labels" . | nindent 4 }}    
  annotations:
    {{- include "vrdbvault.defaultAnnotations" . | nindent 4 }}
automountServiceAccountToken: true