--- # ============================================================= Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    relation: vaultrdb
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels: 
      app: postgres
      relation: vaultrdb
  template:
    metadata:
      labels:
        app: postgres
        relation: vaultrdb
    spec:
      containers:
      - name: postgres
        image: postgres:14
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: scrt-vaultrdb
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources: {}
--- # ============================================================= Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    relation: vaultrdb
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  type: ClusterIP
  selector:
    app: postgres
    relation: vaultrdb