--- # ============================================================= ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vaultrdb
  namespace: vaultrdb
--- # ============================================================= ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultrdb-crole
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jnnkrdb.de
  resources:
  - vaultrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jnnkrdb.de
  resources:
  - vaultrequests/finalizers
  verbs:
  - update
- apiGroups:
  - jnnkrdb.de
  resources:
  - vaultrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
--- # ============================================================= ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vaultrdb-crolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vaultrdb-crole
subjects:
- kind: ServiceAccount
  name: vaultrdb
  namespace: vaultrdb
