--- # ============================================================= Secret
apiVersion: v1
kind: Secret
metadata:
  name: scrt-vaultrdb
type: Opaque
stringData:
  POSTGRES_HOST: postgres.vaultrdb
  POSTGRES_PORT: "5432"
  POSTGRES_USER: vaultmanager
  POSTGRES_PASSWORD: VlJHSVQxMjM0IQ
  POSTGRES_DB : vaultrdb
--- # ============================================================= Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultrdb
  namespace: vaultrdb
spec:
  selector:
    matchLabels:
      control-plane: vaultrdb
  revisionHistoryLimit: 1
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: vaultrdb
    spec:
      containers:
      - name: vaultrdb
        image: docker.io/jnnkrdb/vaultrdb:latest
        envFrom:
        - secretRef:
            name: scrt-vaultrdb
        command:
        - /vaultrdb
        args:
        - --leader-elect
        - --verbosity=5
        - --mode-development
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: vaultrdb
      terminationGracePeriodSeconds: 10
