apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  clusterIP: None
  selector:
    app: etcd-vaultrdb
  ports:
  - name: client
    port: 2379
    targetPort: 2379
  - name: peer
    port: 2380
    targetPort: 2380
  - name: metrics
    port: 2381
    targetPort: 2381
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  selector:
    matchLabels:
      app: etcd-vaultrdb
  serviceName: etcd
  revisionHistoryLimit: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd-vaultrdb
    spec:
      containers:
      - name: etcd
        image: registry.k8s.io/etcd:3.5.6-0
        imagePullPolicy: IfNotPresent
        command:
          - etcd
          - --data-dir=/var/lib/etcd
          - --advertise-client-urls=https://$PODIP:2379
          - --initial-advertise-peer-urls=https://$PODIP:2380
          - --initial-cluster=etcd-0=https://$PODIP:2380
          - --listen-client-urls=https://127.0.0.1:2379,https://$PODIP:2379
          - --listen-metrics-urls=http://127.0.0.1:2381
          - --listen-peer-urls=https://$PODIP:2380
          - --name=etcd-0
        env:
        - name: PODIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        - containerPort: 2381 
          name: metrics
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          failureThreshold: 8
          httpGet:
            host: 127.0.0.1
            path: /health?exclude=NOSPACE&serializable=true
            port: 2381
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        startupProbe:
          failureThreshold: 24
          httpGet:
            host: 127.0.0.1
            path: /health?serializable=false
            port: 2381
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15