--- # ------------------------------------------------------------------------------------------- ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-vrdboperator
  labels:
    {{- include "vrdboperator.labels" . | nindent 4 }}    
  annotations:
    {{- include "vrdboperator.defaultAnnotations" . | nindent 4 }}
automountServiceAccountToken: true