apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    jnnkrdb.de/service: vaultrdb
  name: vaultrdb-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vaultrdb-cr
subjects:
- kind: ServiceAccount
  name: vaultrdb-sa
  namespace: vaultrdb