apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultrdb
  namespace: vaultrdb
spec:
  selector:
    matchLabels:
      jnnkrdb.de/service: vaultrdb
      jnnkrdb.de/type: pod
  replicas: 1
  template:
    metadata:
      labels:
        jnnkrdb.de/service: vaultrdb
        jnnkrdb.de/type: pod
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: vaultrdb
        image: ghcr.io/jnnkrdb/vaultrdb:latest
        imagePullPolicy: 'Always'
        ports:
          - containerPort: 9080 
          - containerPort: 9443 
        env:
        - name: BASICAUTH_USER
          value: "vault"
        - name: BASICAUTH_PASS
          value: "vault"
        - name: VAULTRDB_SERVICENAME
          value: "vaultrdb"
        - name: ENABLE_SWAGGERUI
          value: "true"
        - name: _DEBUG
          value: "false"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        startupProbe:
          httpGet:
            path: /crud/alive
            port: 9080
          timeoutSeconds: 3
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: vaultrdb-sa
      terminationGracePeriodSeconds: 10