apiVersion: v1
kind: Service
metadata:
  name: vaultrdb
  namespace: vaultrdb
spec:
  ports:
    - name: webhook
      port: 443
      protocol: TCP
      targetPort: 9443
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9080
  selector:
    jnnkrdb.de/service: vaultrdb