apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vrdb-storageapi
  namespace: vaultrdb
spec:
  selector:
    matchLabels:
      jnnkrdb.de/service: vrdb
      jnnkrdb.de/type: storageapi
  serviceName: vrdb-storageapi
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        jnnkrdb.de/service: vrdb
        jnnkrdb.de/type: storageapi
    spec:
      terminationGracePeriodSeconds: 10
      volumes: 
        - name: data
          hostPath:
            path: /run/desktop/mnt/host/c/Users/Rodenburger/Documents/GitHub/vaultrdb/_tmp/k8s
      containers:
        - name: vaultrdb-storageapi
          #image: ghcr.io/jnnkrdb/vaultrdb:uiserver-latest
          image: storageapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: data
              mountPath: /opt/vaultrdb/data
          startupProbe:
            httpGet:
              path: /healthz/live
              port: 80
            timeoutSeconds: 3
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 80
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 80
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 16Mi