apiVersion: v1
kind: Service
metadata:
  name: vrdb-storageapi
  namespace: vaultrdb
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    jnnkrdb.de/service: vrdb
    jnnkrdb.de/type: storageapi