--- # ============================================================= Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-vaultrdb
  namespace: vaultrdb
  labels:
    app: postgres-vaultrdb
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: postgres-vaultrdb
  template:
    metadata:
      labels:
        app: postgres-vaultrdb
    spec:
      containers:
      - name: postgres
        image: postgres:14
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: scrt-postgres-vaultrdb
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: vaultrdb
  labels:
    app: postgres-vaultrdb
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  type: ClusterIP
  selector:
    app: postgres-vaultrdb
--- # ============================================================= Secret
apiVersion: v1
kind: Secret
metadata:
  name: scrt-postgres-vaultrdb
  namespace: vaultrdb
type: Opaque
stringData:
  POSTGRES_HOST: postgres.vaultrdb
  POSTGRES_PORT: "5432"

  POSTGRES_USER: vault
  POSTGRES_PASSWORD: VlJHSVQxMjM0IQ
  POSTGRES_DB : vault
