---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jnnkrdb.de
  resources:
  - vrdbconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jnnkrdb.de
  resources:
  - vrdbconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - jnnkrdb.de
  resources:
  - vrdbconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jnnkrdb.de
  resources:
  - vrdbrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jnnkrdb.de
  resources:
  - vrdbrequests/finalizers
  verbs:
  - update
- apiGroups:
  - jnnkrdb.de
  resources:
  - vrdbrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jnnkrdb.de
  resources:
  - vrdbsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jnnkrdb.de
  resources:
  - vrdbsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - jnnkrdb.de
  resources:
  - vrdbsecrets/status
  verbs:
  - get
  - patch
  - update
