# permissions for end users to edit vrdbsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vrdbsecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: vrdbsecret-editor-role
rules:
- apiGroups:
  - jnnkrdb.de
  resources:
  - vrdbsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jnnkrdb.de
  resources:
  - vrdbsecrets/status
  verbs:
  - get
