name: CREATE IMAGE ON TAG

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*' # Push events to every tag not containing /
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHP_TOKEN }}
        
    - name: Build image on Master
      uses: docker/build-push-action@v4
      if: startsWith(github.ref, 'refs/heads/master')
      with:
        # relative path to the place where source code with Dockerfile is located
        context: "."
        tags: |
          ghcr.io/jnnkrdb/vaultrdb:latest
        # build on feature branches, push only on main branch
        push: true
        
    - name: Build image on Tag
      uses: docker/build-push-action@v4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        # relative path to the place where source code with Dockerfile is located
        context: "."
        tags: ${{ steps.meta.outputs.tags }}
        # build on feature branches, push only on main branch
        push: true