name: CREATE IMAGE ON TAG

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master 

env:
  HELM_EXPERIMENTAL_OCI: 1 #enable OCI support

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
        
    - name: Determine Version
      id:   gitversion # id to later be referenced
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        configFilePath: .github/gitversion/GitVersion.yml

    - name: bash-version
      run: |
        echo ${{ steps.gitversion.outputs.semVer }} > ./vaultrdb/VERSION

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHP_TOKEN }}
        
    - name: Build Image Without Push
      uses: docker/build-push-action@v4
      if: github.event_name == 'pull_request'
      with:
        # relative path to the place where source code with Dockerfile is located
        context: "./"
        tags: |
          ghcr.io/jnnkrdb/vaultrdb:${{ steps.gitversion.outputs.semVer }}
          ghcr.io/jnnkrdb/vaultrdb:latest
        # build on feature branches, push only on main branch
        push: false

    - name: Build Image With Push
      uses: docker/build-push-action@v4
      if: github.event_name != 'pull_request'
      with:
        # relative path to the place where source code with Dockerfile is located
        context: "./"
        tags: |
          ghcr.io/jnnkrdb/vaultrdb:${{ steps.gitversion.outputs.semVer }}
          ghcr.io/jnnkrdb/vaultrdb:latest
        # build on feature branches, push only on main branch
        push: true
  
  helm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout repo
    
    - name: install helm
      uses: Azure/setup-helm@v1
      with:
        version: 3.5.0
    
    - name: login to acr using helm
      run: |
        echo ${{ secrets.GHP_TOKEN }} | helm registry login ghcr.io/${{ github.repository_owner }}/vaultrdb --username ${{ github.actor }} --password-stdin

    - name: save helm chart to local registry
      run: |
        helm chart save ${{ github.workspace }}/.helm/ ghcr.io/${{ github.repository_owner }}/vaultrdb:${{ steps.gitversion.outputs.semVer }}

    - name: publish chart to acr
      run: |
        helm chart push ghcr.io/${{ github.repository_owner }}/vaultrdb:${{ steps.gitversion.outputs.semVer }}